EXAMPLES = {
    "Head Shaver": {"Attribute": ["Brand Name", "Color", "Special Feature", "Material"], "Value": ["Telfun", "Head Shaver for Men", "Fast Charging", "Stainless Steel"], 'image': 'https://m.media-amazon.com/images/I/715qUxAK-iL._SX466_.jpg', 'title': 'Telfun Head Shavers for Bald Men, 5-in-1 Electric Razor for Men w/h LED Display, IPX7-Waterproof, Faster-Charging Mens Grooming Kit w/h Beard Trimmer, Nose Hair & Hair Clippers, Facial Cleaning Brush', 'new_attributes': ['ss']},
    "Laptop": {"Attribute": ["Brand", "Series", "Screen Size", "RAM", "Processor", "Hard Disk Size", "Operating System", "graphics coprocessor", "card description"], "Value": ["HP", "HP Pavillion", "15.6 inches", "12 GB", "Core i5", "Intel Iris Xe Graphics", "256 GB", "Windows 10", "Integrated"], 'image': 'https://m.media-amazon.com/images/I/61T+AmPtuDL._AC_SX466_.jpg', 'title': 'HP Pavilion 15.6" FHD IPS Touchscreen Premium Laptop | 11th Gen Intel Core i5-1135G7 | Intel Iris Xe Graphics | 12GB RAM | 256GB SSD | WiFi | HDMI | Windows 10 | Silver', 'new_attributes': ['Connectivity', 'Color', 'Monitor Resolution']},
    "Monitor": {"Attribute": ["Brand", "Special Feature", "Color", "Number of Component Outputs", "Refresh Rate", "Resolution"], "Value": ["Philips Computer Monitors", "Curved Screen, Blue Light Filter, Anti-Glare Coating, Wall Mountable, Frameless, Tilt Adjustment, Flicker-Free, Built-In Speakers", "Black", "HDMI", "1080p", "75Hz"], 'image': 'https://m.media-amazon.com/images/I/61Ms+E8-ZEL._AC_SX679_.jpg', 'title': 'Philips 241V8L 24 "LED VA Full HD monitor, 1920 x 1080, Gaming Adaptive Sync, 75 Hz, HDMI, VGA, VESA connection, Black', 'new_attributes': ['HD Type', 'Display Type', 'Video Connector Type']},
    "Personal Computer": {"Attribute": ["Hard Drive", "Brand Name", "Item model number", "Item Weight", "Product Dimensions", "Processor Count", "Type"], "Value": ["4 TB Desktop", "Toshiba", "Black", "6 pounds", "14 x 11 x 11 inches", "1", "Network Attached Storage"], 'image': 'https://m.media-amazon.com/images/I/51manTbP2PL._AC_SX679_.jpg', 'title': 'PC Desktop Cpu i5 11400 Up 4.40 GHZ / Gpu UHD 730 Dvi-D - Hdmi - Display-Port / Ram 16Gb Ddr4 / Ssd M.2 NVMe 500Gb / Wi-Fi Usb 3.0 / Windows 11 / Computer Office Home Complete', 'new_attributes': ["RAM", "Processor", "Hard Disk Size", "Operating System", 'Processor Speed', 'Connectivity']},
    "Gaming Computer": {"Attribute": ['Operating System', 'RAM', 'Brand Name', 'Computer Memory Type', 'Series', 'Processor Brand'], 'Value': ['Windows 10', '8 GB', 'Gamer Ultra', 'DDR3 SDRAM', 'CyberpowerPC', 'AMD'], 'image': 'https://m.media-amazon.com/images/I/81fqadZxgOL._AC_SX466_.jpg', 'title': 'CyberpowerPC Gamer Ultra Gaming PC, AMD FX-6300 3.5GHz, Radeon R7 240 2GB, 8GB DDR3, 1TB HDD, WiFi & Win 10 Home (GUA884)', 'new_attributes': ["Graphics Processor", 'Processor Speed', 'Connectivity']},
    "Graphics Card": {"Attribute": ['Model Name', 'Brand', 'Graphics Processor', 'Video Output Interface', 'Graphics Card Ram Size'], 'Value': ['MSI Geforce 210 1024 MB DDR3 PCI-Express 2.0 Graphics Card MD1G/D3', 'MSI', 'NVIDIA GeForce', 'VGA, DVI, HDMI', '2'], 'image': 'https://m.media-amazon.com/images/I/515LrrMQw8L._AC_.jpg', 'title': 'MSI Geforce 210 1024 MB DDR3 PCI-Express 2.0 Graphics Card MD1G/D3', 'new_attributes': ['Interface', 'Video Memory Type']},
    "Game Controller": {'Attribute': ['Hardware Platform', 'Brand', 'Color', 'Operating System', 'Connectivity Technology'], 'Value': ['Android/iOS', 'GameSir', 'G4 Pro 2', 'Windows Vista;Windows XP;Mac;Linux', 'Bluetooth, Wi-Fi, USB'], 'image': 'https://m.media-amazon.com/images/I/61u6dyNEqOS._AC_SX679_.jpg', 'title': 'GameSir G4 Pro Bluetooth Game Controller 2.4GHz Wireless Gamepad for Nintendo Switch Apple Arcade and MFi Game Xbox Cloud Gaming', 'new_attributes': ['Interface', 'Video Memory Type']},
    "USB": {'Attribute': ['Brand Name', 'Item Model Number', 'Item Weight', 'Color', 'Capacity'], 'Value': ['SanDisk', 'SDCZ48-064G USB 3.0 Flash Drive', '0.32 ounces', 'Black', '64GB'], 'image': 'https://m.media-amazon.com/images/I/61TuPtmTScL._AC_SX466_.jpg', 'title': 'SanDisk - SDCZ48-064G-UAM46 64GB Ultra USB 3.0 Flash Drive - SDCZ48-064G-UAM46 Black', 'new_attributes': ['Format', 'Type']},
    "Digital Camera": {'Attribute': ['Brand Name', 'Item Weight', 'Product Dimensions', 'Item model number', 'Special Feature', 'Color Name', 'Type'], 'Value':['Nikon', '5 pounds', '16 x 12 x 8 inches', 'Nikon d3200', 'Alcohol Free', 'Black', 'Digital SLR Camera'], 'image': 'https://m.media-amazon.com/images/I/91WSe2OKasL._AC_SX679_.jpg', 'title': 'Nikon D3200 24.2MP CMOS Digital SLR with 18-55mm f/3.5-5.6 Auto Focus-S DX VR NIKKOR Zoom Lens (Black)', 'new_attributes': ['Resolution', 'Sensor Size', 'Sensor Type']},
    "Laptop 1": {'Attribute': ['Brand', 'Item Model Number', 'Screen Size', 'Processor', 'RAM', 'Hard Disk Size', 'Processor Speed', 'Operating System'], "Value": ['Dell', 'Latitude E6420', '14.1-Inch', 'Core i5', '6 GB RAM', '256 GB SSD', '2.5GHz', 'Windows 7'], 'title': 'Dell Latitude E6420 Premium-Built 14.1-Inch Business Laptop (Intel Core i5 2.5GHz with 3.2G Turbo Frequency, 6G RAM, 256G, Windows 7 Home 64-bit', 'image': 'https://m.media-amazon.com/images/I/51y8MIjhkYL._AC_.jpg', 'new_attributes': ['Processor Speed']},
    "Laptop 2": {'Attribute': ['Brand', 'Screen Size', 'Clock Speed', 'Ram', 'Hard Disk', 'Processor', 'Connectivity', 'Operating System', 'Resolution'], 'Value': ['Lenovo', '15.6\"', 'Core i7', '8 GB RAM', '1 TB', '3.2 GHz', 'Wi-Fi', 'Windows 8', '1920 x 1080'], 'title': 'Lenovo ThinkPad Yoga 15 15.6\" IPS Full HD 1920 x 1080 2-in-1 Ultrabook Laptop PC Intel Core i7-7200U 8GB DDR3L Memory 1TB SSD NVIDIA Geforce 840M Wi-Fi Windows 8.1', 'image': 'https://m.media-amazon.com/images/I/61QC3+WD1qL._AC_SX522_.jpg', 'new_attributes': ['speed']}
}
