EXAMPLES = {
    "Head Shaver": {"Attribute": ["Brand Name", "Color", "Special Feature", "Material"], "Value": ["Telfun", "Head Shaver for Men", "Fast Charging", "Stainless Steel"], 'image': 'https://m.media-amazon.com/images/I/715qUxAK-iL._SX466_.jpg', 'title': 'Telfun Head Shavers for Bald Men, 5-in-1 Electric Razor for Men w/h LED Display, IPX7-Waterproof, Faster-Charging Mens Grooming Kit w/h Beard Trimmer, Nose Hair & Hair Clippers, Facial Cleaning Brush'},
    "Laptop": {"Attribute": ["Brand", "Series", "Screen Size", "RAM", "Processor", "Hard Disk Size", "Operating System", "graphics coprocessor", "card description"], "Value": ["HP", "HP Pavillion", "15.6 inches", "12 GB", "Core i5", "Intel Iris Xe Graphics", "256 GB", "Windows 10", "Integrated"], 'image': 'https://m.media-amazon.com/images/I/61T+AmPtuDL._AC_SX466_.jpg', 'title': 'HP Pavilion 15.6" FHD IPS Touchscreen Premium Laptop | 11th Gen Intel Core i5-1135G7 | Intel Iris Xe Graphics | 12GB RAM | 256GB SSD | WiFi | HDMI | Windows 10 | Silver', 'new_attributes': ['Connectivity', 'Color', 'Monitor Resolution']},
    "Monitor": {"Attribute": ["Brand", "Special Feature", "Color", "Number of Component Outputs", "Refresh Rate", "Resolution"], "Value": ["Philips Computer Monitors", "Curved Screen, Blue Light Filter, Anti-Glare Coating, Wall Mountable, Frameless, Tilt Adjustment, Flicker-Free, Built-In Speakers", "Black", "HDMI", "1080p", "75Hz"], 'image': 'https://m.media-amazon.com/images/I/61Ms+E8-ZEL._AC_SX679_.jpg', 'title': 'Philips 241V8L 24 "LED VA Full HD monitor, 1920 x 1080, Gaming Adaptive Sync, 75 Hz, HDMI, VGA, VESA connection, Black', 'new_attributes': ['HD Type', 'Display Type', 'Video Connector Type']},
    "Personal Computer": {"Attribute": ["Hard Drive", "Brand Name", "Item model number", "Item Weight", "Product Dimensions", "Processor Count", "Type"], "Value": ["4 TB Desktop", "Toshiba", "Black", "6 pounds", "14 x 11 x 11 inches", "1", "Network Attached Storage"], 'image': 'https://m.media-amazon.com/images/I/51manTbP2PL._AC_SX679_.jpg', 'title': 'PC Desktop Cpu i5 11400 Up 4.40 GHZ / Gpu UHD 730 Dvi-D - Hdmi - Display-Port / Ram 16Gb Ddr4 / Ssd M.2 NVMe 500Gb / Wi-Fi Usb 3.0 / Windows 11 / Computer Office Home Complete', 'new_attributes': ["RAM", "Processor", "Hard Disk Size", "Operating System", 'Processor Speed', 'Connectivity']},
    "Gaming Computer": {"Attribute": ['Operating System', 'RAM', 'Brand Name', 'Computer Memory Type', 'Series', 'Processor Brand'], 'Value': ['Windows 10', '8 GB', 'Gamer Ultra', 'DDR3 SDRAM', 'CyberpowerPC', 'AMD'], 'image': 'https://m.media-amazon.com/images/I/81fqadZxgOL._AC_SX466_.jpg', 'title': 'CyberpowerPC Gamer Ultra Gaming PC, AMD FX-6300 3.5GHz, Radeon R7 240 2GB, 8GB DDR3, 1TB HDD, WiFi & Win 10 Home (GUA884)', 'new_attributes': ["Graphics Processor", 'Processor Speed', 'Connectivity']},
    "Graphics Card": {"Attribute": ['Model Name', 'Brand', 'Graphics Processor', 'Video Output Interface', 'Graphics Card Ram Size'], 'Value': ['MSI Geforce 210 1024 MB DDR3 PCI-Express 2.0 Graphics Card MD1G/D3', 'MSI', 'NVIDIA GeForce', 'VGA, DVI, HDMI', '2'], 'image': 'https://m.media-amazon.com/images/I/515LrrMQw8L._AC_.jpg', 'title': 'MSI Geforce 210 1024 MB DDR3 PCI-Express 2.0 Graphics Card MD1G/D3', 'new_attributes': ['Interface', 'Video Memory Type']},
    "Game Controller": {'Attribute': ['Hardware Platform', 'Brand', 'Color', 'Operating System', 'Connectivity Technology'], 'Value': ['Android/iOS', 'GameSir', 'G4 Pro 2', 'Windows Vista;Windows XP;Mac;Linux', 'Bluetooth, Wi-Fi, USB'], 'image': 'https://m.media-amazon.com/images/I/61u6dyNEqOS._AC_SX679_.jpg', 'title': 'GameSir G4 Pro Bluetooth Game Controller 2.4GHz Wireless Gamepad for Nintendo Switch Apple Arcade and MFi Game Xbox Cloud Gaming', 'new_attributes': ['Interface', 'Video Memory Type']},
    "USB": {'Attribute': ['Brand Name', 'Item Model Number', 'Item Weight', 'Color', 'Capacity'], 'Value': ['SanDisk', 'SDCZ48-064G USB 3.0 Flash Drive', '0.32 ounces', 'Black', '64GB'], 'image': 'https://m.media-amazon.com/images/I/61TuPtmTScL._AC_SX466_.jpg', 'title': 'SanDisk - SDCZ48-064G-UAM46 64GB Ultra USB 3.0 Flash Drive - SDCZ48-064G-UAM46 Black', 'new_attributes': ['Format', 'Type']}
}

